/* Each new term in the Fibonacci sequence is
generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequenc
e whose values do not exceed four million,
find the sum of the even-valued terms. */

let fibonacci = (n) => {
    var dp = [];
    dp[0] = 1;
    dp[1] = 1;

    for(var i = 2; i <= n; ++i) {
        dp[i] = dp[i - 1] + dp[i - 2];
    }

    return dp[n];
}

let sum = 0;

for(var i = 0; i < 33; ++i) {
    if(fibonacci(i) % 2 == 0) {
        sum += fibonacci(i);
    }
}
console.log(sum); //4613732
